### ISSUE TITLE
Accept initial governance documentation

### ISSUE THREAD

**Issue by omad** [opendatacube/governance#1]
At the recent CEOS Data Cube meeting we agreed to work out some initial governance documents. Lets try and get them in order by the end of next Monday (March 27), before we turn on *branch protection* to limit the changes to pull request approved ones.

Please take some time to review and make any minor changes directly on the *master* branch. This includes things you think are non-controversial like typos/links/styling/minor sentence structure fixes, etc.

For anything you think may require further discussion, please open either a github issue or pull request and we'll discuss the change.

On March 28 I'll enable *branch protection*, and email the ODC google group to put this in front of a wider audience.

**Comment by woodcockr** [comment]
Hi

I've made some minor editorial changes to the documents (see the commit log) and also added back the Benevolent Dictator role noting it is a temporary appointment for a fixed term (6 months was my initial suggestion) and selected on a rotating basis from the Steering Committee. 
This should be fairly consistent with our discussion at the Open Data Cube launch workshop but I had to add some specifics for it to make sense.

There is one line in the Jupyter version of the newsubprojects.md document that doesn't exist in the Open Data Cube one (removed because of the initial removal of the BDFL). The pertinent line is that
"BDFL pronouncement could still be used to make an acceptance call if judged necessary" to incorporate a new proposal.

The wording in governance.md would implicitly allow for thus override but it is not mentioned in newprojects.md specifically as it is in the Jupyter version. I don't believe we need to make this explicit and prefer the emphasis on using the SC, which is also what the governance.md encourages for the BD to do.

The BD also takes on the role of chairing the SC for the specified term so they are responsible for helping to ensure the SC remains engaged in the process properly.

**Comment by omad** [comment]
Awesome, this is starting to come together nicely.

Although we were all on-board with the _All Powerful Steering Council Leader_ at the initial meeting, a few people have expressed reservations afterwards. It would be nice to get more opinions in here.

Reservations include:
- ~~Cultural sensitivities around naming~~ (Suggested name of _Chair_ sounds great)
- There's no existing and obvious candidate
- Too much potential power invested in one person and they could possibly derail the ODC project

I think that having the Chair as a rotating position mostly mitigates these issues, and the name change makes it sound significantly less scary. If we have a specified order which includes having the position switching between Institutions I don't have any issue with it.

I do wonder if the wording of the position indicates more power than would be held. I doubt we would follow the decision of a Chair we disagree with, other than when we have already agreed to defer to them. Perhaps the wording should indicate this, perhaps by swapping around the parts about 

> The Chair has the authority to make all final decisions 

and 

> It is expected that the Chair will only rarely assert his/her final authority. ... When it does occur, the Chair override typically happens in situations where there is a deadlock 

Maybe it doesn't matter, but I'd be interested to hear others thoughts.

**Comment by woodcockr** [comment]
> There's no existing and obvious candidate
- There can't be an existing candidate if the Steering Committee hasn't been established
-  no obvious candidate? if  there is no one on the Steering Council capable of being the Chair, why are they on the Steering Council and why is there one? Personally I think any of the proposed members are capable individuals interested in the success of ODC community as a whole, even noting the speciality differences.

I am assuming this reservation must be about something else as it makes little sense in its current form.

I would anticipate the roles authority is rarely used - as suggested in the wording. I would also suggest that it is presumptuous at best to assume that the role of Chair would be abused by any member of the Steering Committee. Indeed, if someone of such character was seeking to join the Steering Committee I suspect that would be vetoed to start with since it is unlikely they are a collaborative and effective member of the ODC community in the first place and thus couldn't be on the Steering committee at all.

**Comment by tdhu** [comment]
I tend to agree with Damien - there were reservations about the position and its necessity that have been largely mitigated by the rotating nature of the position and Damien's suggested wording where we are explicit in the expectation that this is a rarely used authority (rather than having this as something we anticipate).

**Comment by woodcockr** [comment]
The wording being referenced is taken directly from the Jupyter governance model as was agreed to be used as a model at the workshop meeting a few weeks back. I don't believe anyone at anytime has suggested that the authority of the Chair is anything other than an special authority to be used under those circumstances where particularly arbitrary and deadlock decisions occur but also perhaps "group think" choices that would act against the Projects best interests.

I have a lot of confidence in any member that meets the membership criteria for the Steering Council being an appropriate user of this authority and appreciate the strength this role can bring to the Governance when a committee loses direction as they all to often do when there is no circuit breaker.

**Comment by omad** [comment]
Thanks everyone. We've gotten to a good starting point. Branch protection is now enabled, so any changes will need to be made through a reviewed Pull Request.

If you need assistance with this, ask your friendly neighbourhood GitHub Wizard and they'll be happy to help.
