### ISSUE TITLE
Remove references to"copyright XXX"

### ISSUE THREAD

**Issue by GypsyBojangles** [opendatacube/governance#8]
Advice that we have sought within the agency from our contract management team has indicated that lines such as "copyright XXX" should be removed.
 We (GA) are continuing to pursue this with advice from our parent department, however this currently preventing greater collaboration with USGS.

**Comment by woodcockr** [comment]
Sounds like this is related to the issue I raised at the ODC workshop regarding transfer of copyright ownership so that such things could be made clear.
Note that in some jurisdictions, Australia included unless the legislation changed, Copyright is inherently granted and doesn't require a copyright label to be included (which last I checked was required in the USA for example).
